# Generated by Django 3.2.9 on 2021-11-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fullname',
            new_name='name',
        ),
    ]
